PROC SQL ;
  TITLE "Filesize for CARS Data Set" ;
  SELECT LIBNAME,
         MEMNAME,
         FILESIZE FORMAT=SIZEKMG.,
         FILESIZE FORMAT=SIZEK.
    FROM DICTIONARY.TABLES
      WHERE LIBNAME = "SASHELP"
        AND MEMNAME = "CARS"
        AND MEMTYPE = "DATA" ;
QUIT ;